[package]
name = "lancev"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
lance = "10.0.0"
lance-file = "10.0.0"
lance-io = "10.0.0"
object_store = "0.13.2"
opaline = "0.4.1"
prost = "0.14.4"
prost-types = "0.14.4"
ratatui = "0.30.2"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
